---
title: "Pixel: Endocarditis"
author: "Anish Sanjay Shah, MD/MS<br><span style = 'font-size: 70%;'>Cardiology Fellow<br>University of Illinois at Chicago</span>"
output:
  xaringan::moon_reader:
    self_contained: true
    nature:
      titleSlideClass: [left, middle, inverse]
      highlightLines: true
---

```{r setup, echo = FALSE, include = FALSE}
library(tidyverse)
library(gt)

print.tbl_df <- function(x, ...) {
	print.data.frame(x, right = FALSE, ...)
	invisible(x)
}

# Options
options(digits = 2)
```
	
```{r, knitr, include=FALSE}
knitr::opts_chunk$set(
   fig.retina = 3,
   warning = FALSE,
   message = FALSE,
   echo = FALSE,
   cache = TRUE
)
```

---
# Transthoracic Parasternal Long Axis

---

<video>
<source src="resources/9262-1086-4143-0176_series_16.mp4" type="video/mp4">
</video>


---

9262-1086-4143-0176_series_42.mp4
9262-1086-4143-0176_series_5.mp4
9462-1086-5913-0147_series_42.mp4

9262-1086-4143-0176_series_40.mp4
9262-1086-4143-0176_series_45.mp4
9462-1086-5913-0147_series_29.mp4

9262-1086-4143-0176_series_41.mp4
9262-1086-4143-0176_series_47.mp4
9462-1086-5913-0147_series_3.mp4
